# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyns_auto
from pyns_auto.models.apiruns_task import ApirunsTask  # noqa: E501
from pyns_auto.rest import ApiException


class TestApirunsTask(unittest.TestCase):
    """ApirunsTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApirunsTask(self):
        """Test ApirunsTask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyns_auto.models.apiruns_task.ApirunsTask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
