# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyns_auto
from pyns_auto.api.run_api import RunApi  # noqa: E501
from pyns_auto.rest import ApiException


class TestRunApi(unittest.TestCase):
    """RunApi unit test stubs"""

    def setUp(self):
        self.api = pyns_auto.api.run_api.RunApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_runs_get(self):
        """Test case for api_runs_get

        Returns list of runs.  # noqa: E501
        """
        pass

    def test_api_runs_run_id_get(self):
        """Test case for api_runs_run_id_get

        Get run by id.  # noqa: E501
        """
        pass

    def test_api_tasks_get(self):
        """Test case for api_tasks_get

        Returns list of tasks.  # noqa: E501
        """
        pass

    def test_api_tasks_task_id_get(self):
        """Test case for api_tasks_task_id_get

        Get task by id.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
