# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyns_auto
from pyns_auto.models.body_3 import Body3  # noqa: E501
from pyns_auto.rest import ApiException


class TestBody3(unittest.TestCase):
    """Body3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody3(self):
        """Test Body3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyns_auto.models.body_3.Body3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
