# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyns_auto
from pyns_auto.models.inline_response_default_1 import InlineResponseDefault1  # noqa: E501
from pyns_auto.rest import ApiException


class TestInlineResponseDefault1(unittest.TestCase):
    """InlineResponseDefault1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponseDefault1(self):
        """Test InlineResponseDefault1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyns_auto.models.inline_response_default_1.InlineResponseDefault1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
