# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyns_auto
from pyns_auto.models.inline_response_default_5 import InlineResponseDefault5  # noqa: E501
from pyns_auto.rest import ApiException


class TestInlineResponseDefault5(unittest.TestCase):
    """InlineResponseDefault5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponseDefault5(self):
        """Test InlineResponseDefault5"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyns_auto.models.inline_response_default_5.InlineResponseDefault5()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
